# FROM afif2100/docker-base
FROM nvcr.io/nvidia/tensorflow:22.07-tf2-py3
RUN apt-get update && \
    apt-get -y install gcc mono-mcs manpages-dev git make

USER $USER
COPY . $WORKDIR

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["bash", "run_app.sh"]
