FROM python:3.8.13-slim-buster

RUN apt-get update && \
    apt-get -y install gcc mono-mcs manpages-dev git make
USER root

ENV WORKDIR=/usr/src/app

RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR
COPY . $WORKDIR

RUN mkdir /.local && \
    mkdir /.cache && \
    chown -R 1000.1000 /usr/src/app && \
    chown -R 1000.1000 /.local && \
    chown -R 1000.1000 /.cache

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install redis