apiVersion: v1
kind: Service
metadata:
  name: falcon-app-load-balancer
spec:
  selector:
    app: falcon-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 6000
      nodePort: 30002
  type: LoadBalancer
  # type: NodePort
  # externalIPs:
    # - 172.17.0.2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-app
spec:
  selector:
    matchLabels:
      app: falcon-app
  replicas: 2
  template:
    metadata:
      labels:
        app: falcon-app
    spec:
      containers:
      - name: falcon-test-container
        image: afif2100/falcon-app:latest
        imagePullPolicy: Always #IfNotPresent #Always
        # env:
        #   - name: ENABLE_DB_CHECK
        #   - name: REDIS_HOST
        #   - name: REDIS_PORT
        #   - name: REDIS_PASSWORD
        ports:
          - containerPort: 6000
        resources:
          requests:
            cpu: 0.1
          limits:
            cpu: 0.2

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: falcon-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: falcon-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70