
name: sentiment-app/build

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/110817751945/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-pool-provider-2'
        service_account: 'mlflow-user@hvzn-development.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Use gsutil LS'
      run: 'gsutil ls gs://hvzn-gcs-us-1'

    - name: Build and publish image to GCR
      uses: carbonchain/action-container-registry@v1.1
      with:
        project_id: hvzn-development
        dockerfile: apis/sentiment_app/Dockerfile
        image: asia.gcr.io/hvzn-development/afif2100/sentiment-app
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    # - id: 'deploy'
    #   uses: 'google-github-actions/deploy-cloudrun@v0'
    #   with:
    #     service: 'hello-cloud-run'
    #     image: "asia.gcr.io/hvzn-development/afif2100/sentiment-app"

    # - name: 'Use output'
    #   run: 'curl "${{ steps.deploy.outputs.url }}"'
