name: fastapi-app/build_and_deploy

on:
  pull_request:
    paths:
      - "apis/fastapi_boilerplate/*"

env:
  FOLDER_NAME: fastapi_boilerplate
  APP_NAME: fastapi-app
  SERVICE_NAME: afif2100-fastapi-app

jobs:
  build:
    name: build docker and push
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/110817751945/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-pool-provider-2"
          service_account: "mlflow-user@hvzn-development.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          # gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
          registry: asia.gcr.io
          project_id: hvzn-development
          image_name: afif2100/fastapi-app
          image_tag: latest,${{ github.sha }}
          dockerfile: ./apis/fastapi_boilerplate/Dockerfile
          context: ./apis/fastapi_boilerplate

      # - name: Build and publish image to GCR
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./apis/$FOLDER_NAME
      #     file: ./apis/$FOLDER_NAME/Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       asia.gcr.io/hvzn-development/afif2100/$APP_NAME:${{ github.sha }}
      #       asia.gcr.io/hvzn-development/afif2100/$APP_NAME:latest

  deploy:
    name: deploy docker on cloud run
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/110817751945/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-pool-provider-2"
          service_account: "mlflow-user@hvzn-development.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "$SERVICE_NAME"
          region: asia-southeast2
          image: "asia.gcr.io/hvzn-development/afif2100/$APP_NAME:latest"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}/health"'
